admin_author:
    resource: "@AdminBundle/Controller/AuthorController.php"
    type:     annotation

admin_post:
    resource: "@AdminBundle/Controller/PostController.php"
    type:     annotation



admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin




# model:
#     resource: "@ModelBundle/Controller/"
#     type:     annotation
#     prefix:   /

core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /
 
# core:
#     resource: "@CoreBundle/Resources/config/routing.yml"
#     prefix:   /
    
# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation
