<?php

namespace Blog\ModelBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    
    /**
     * @param int $num
     * 
     * 
     * @return array()
     **/
    
    
    
    public function getLatest($num)
    {
        
        
     $db=$this->getQueryBuilder()->orderBy('p.createdAt','desc')->setMaxResults($num);
              
              
              
              
     return $db->getQuery()->getResult();   
        
        
    }
    
    
    private function getQueryBuilder(){
        
        
      $rm=$this->getEntityManager();
      
      dump($rm);
      
      
      $db=$rm->getRepository('ModelBundle:Post')->createQueryBuilder('p');
      
                                               
      
        
      return $db;  
        
    }
    
    /**
     * 
     *return first post 
     * 
     * @return Post
     **/
    public function findFirst()
    {
        
        
     $db=$this->getQueryBuilder()->orderBy('p.id','asc')->setMaxResults(1);
              
              
              
              
     return $db->getQuery()->getSingleResult();   
        
        
    }
    
}
